### ISSUE TITLE
voomWithDreamWeights - Error in weightsMatrix * out$weights: non-conformable arrays

### ISSUE THREAD

**Issue by AnnaSophieFroehlich** [GabrielHoffman/dreamlet#13]
Hi,

Thank you for your great package.

I am running into an issue when running processAssays() with certain cell types.

Please see the example code below:

```
# Load libraries
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(zellkonverter)
library(dreamlet)
library(rhdf5)
library(HDF5Array)})

#read H5AD files
file <- "../datasets/adata_annotated.h5ad"
sce <- readH5AD(file, use_hdf5=TRUE, verbose=FALSE)

#Compute pseudobulk
pb <- aggregateToPseudoBulk(sce,
    assay = "counts",     
    cluster_id = “annotated_celltypes",  
    sample_id = "sample", 
    BPPARAM = SnowParam(6, progressbar=TRUE))

#Normalize and apply voom
form <- ~ (1|Batch) + (1|Sex) + (1|Disease) + Age + SV1 + SV2 + SV3 + SV4

res.proc_celltype <- processAssays(pb, form, assays='celltype' min.count=10, 
min.prop=0.8, min.cells=5, min.samples=50, BPPARAM = SnowParam(12))
```

> celltype...
> 
> Error in weightsMatrix * out$weights: non-conformable arrays
> Traceback:
> 
> 1. processAssays(pb, form, assays = “celltype”, min.count = 10, 
>  .     min.prop = 0.8, min.cells = 5, min.samples = 50, BPPARAM = SnowParam(12))
> 2. lapply(assays, function(k) {
>  .     if (!quiet) 
>  .         message("  ", k, "...", appendLF = FALSE)
>  .     startTime <- Sys.time()
>  .     y <- assay(sceObj, k)
>  .     n.cells <- n.cells_full[colnames(y), k, drop = FALSE]
>  .     data <- merge_metadata(data_constant, metadata(sceObj)$aggr_means, 
>  .         k, metadata(sceObj)$agg_pars$by)
>  .     res <- processOneAssay(y[, rownames(data), drop = FALSE], 
>  .         formula = formula, data = data, n.cells = n.cells[rownames(data), 
>  .             , drop = FALSE], min.cells = min.cells, min.count = min.count, 
>  .         min.samples = min.samples, min.prop = min.prop, isCounts = isCounts, 
>  .         normalize.method = normalize.method, useCountsWeights = useCountsWeights, 
>  .         span = span, BPPARAM = BPPARAM, ...)
>  .     if (!quiet) 
>  .         message(format(Sys.time() - startTime, digits = 2))
>  .     res
>  . })
> 3. FUN(X[[i]], ...)
> 4. processOneAssay(y[, rownames(data), drop = FALSE], formula = formula, 
>  .     data = data, n.cells = n.cells[rownames(data), , drop = FALSE], 
>  .     min.cells = min.cells, min.count = min.count, min.samples = min.samples, 
>  .     min.prop = min.prop, isCounts = isCounts, normalize.method = normalize.method, 
>  .     useCountsWeights = useCountsWeights, span = span, BPPARAM = BPPARAM, 
>  .     ...)
> 5. voomWithDreamWeights(y[keep, ], formula, data, weights = w_cells, 
>  .     BPPARAM = BPPARAM, ..., save.plot = TRUE, quiet = quiet, 
>  .     span = span, hideErrorsInBackend = TRUE)
> 

`sessionInfo()`

> R version 4.3.1 (2023-06-16)
> Platform: x86_64-conda-linux-gnu (64-bit)
> Running under: CentOS Linux 7 (Core)
> 
> Matrix products: default
> BLAS/LAPACK: /conda-envs/dreamlet/lib/libopenblasp-r0.3.24.so;  LAPACK version 3.11.0
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> time zone: Europe/Berlin
> tzcode source: system (glibc)
> 
> attached base packages:
> [1] stats4    stats     graphics  grDevices utils     datasets  methods  
> [8] base     
> 
> other attached packages:
>  [1] readxl_1.4.3                HDF5Array_1.28.1           
>  [3] DelayedArray_0.27.10        SparseArray_1.1.12         
>  [5] S4Arrays_1.1.6              abind_1.4-5                
>  [7] Matrix_1.6-1.1              rhdf5_2.44.0               
>  [9] dreamlet_0.99.28            variancePartition_1.31.20  
> [11] BiocParallel_1.35.4         limma_3.57.10              
> [13] ggplot2_3.4.4               zellkonverter_1.11.3       
> [15] SingleCellExperiment_1.23.0 SummarizedExperiment_1.31.1
> [17] Biobase_2.61.0              GenomicRanges_1.53.2       
> [19] GenomeInfoDb_1.37.6         IRanges_2.35.3             
> [21] S4Vectors_0.39.3            BiocGenerics_0.47.0        
> [23] MatrixGenerics_1.12.2       matrixStats_1.0.0          
> 
> loaded via a namespace (and not attached):
>   [1] splines_4.3.1             pbdZMQ_0.3-10            
>   [3] bitops_1.0-7              filelock_1.0.2           
>   [5] tibble_3.2.1              cellranger_1.1.0         
>   [7] basilisk.utils_1.13.3     graph_1.79.4             
>   [9] XML_3.99-0.14             lifecycle_1.0.3          
>  [11] Rdpack_2.5                mixsqp_0.3-48            
>  [13] edgeR_3.99.2              lattice_0.21-9           
>  [15] MASS_7.3-60               backports_1.4.1          
>  [17] magrittr_2.0.3            reticulate_1.34.0        
>  [19] DBI_1.1.3                 minqa_1.2.6              
>  [21] zlibbioc_1.47.0           EnvStats_2.8.1           
>  [23] purrr_1.0.2               rmeta_3.0                
>  [25] msigdbr_7.5.1             RCurl_1.98-1.12          
>  [27] GenomeInfoDbData_1.2.10   ggrepel_0.9.4            
>  [29] pbkrtest_0.5.2            irlba_2.3.5.1            
>  [31] annotate_1.79.0           DelayedMatrixStats_1.23.9
>  [33] codetools_0.2-19          tidyselect_1.2.0         
>  [35] lme4_1.1-34               base64enc_0.1-3          
>  [37] jsonlite_1.8.7            iterators_1.0.14         
>  [39] tools_4.3.1               progress_1.2.2           
>  [41] snow_0.4-4                Rcpp_1.0.11              
>  [43] zenith_1.3.1              glue_1.6.2               
>  [45] IRdisplay_1.1             dplyr_1.1.3              
>  [47] withr_2.5.1               numDeriv_2016.8-1.1      
>  [49] fastmap_1.1.1             basilisk_1.13.4          
>  [51] boot_1.3-28.1             rhdf5filters_1.12.1      
>  [53] fansi_1.0.5               caTools_1.18.2           
>  [55] digest_0.6.33             truncnorm_1.0-9          
>  [57] R6_2.5.1                  colorspace_2.1-0         
>  [59] scattermore_1.2           gtools_3.9.4             
>  [61] RSQLite_2.3.1             RhpcBLASctl_0.23-42      
>  [63] utf8_1.2.3                tidyr_1.3.0              
>  [65] generics_0.1.3            data.table_1.14.8        
>  [67] corpcor_1.6.10            prettyunits_1.2.0        
>  [69] httr_1.4.7                pkgconfig_2.0.3          
>  [71] gtable_0.3.4              blob_1.2.4               
>  [73] XVector_0.41.1            remaCor_0.0.16           
>  [75] htmltools_0.5.6.1         GSEABase_1.63.0          
>  [77] scales_1.2.1              png_0.1-8                
>  [79] fANCOVA_0.6-1             ashr_2.2-63              
>  [81] reshape2_1.4.4            uuid_1.1-1               
>  [83] nlme_3.1-163              nloptr_2.0.3             
>  [85] repr_1.1.6                cachem_1.0.8             
>  [87] stringr_1.5.0             KernSmooth_2.23-22       
>  [89] parallel_4.3.1            RcppZiggurat_0.1.6       
>  [91] AnnotationDbi_1.63.2      pillar_1.9.0             
>  [93] grid_4.3.1                vctrs_0.6.4              
>  [95] gplots_3.1.3              mashr_0.2.69             
>  [97] xtable_1.8-4              Rgraphviz_2.45.0         
>  [99] evaluate_0.22             KEGGgraph_1.61.0         
> [101] invgamma_1.1              mvtnorm_1.2-3            
> [103] cli_3.6.1                 locfit_1.5-9.8           
> [105] compiler_4.3.1            rlang_1.1.1              
> [107] crayon_1.5.2              SQUAREM_2021.1           
> [109] plyr_1.8.9                stringi_1.7.12           
> [111] assertthat_0.2.1          babelgene_22.9           
> [113] lmerTest_3.1-3            munsell_0.5.0            
> [115] Biostrings_2.69.2         aod_1.3.2                
> [117] dir.expiry_1.9.0          IRkernel_1.3.2           
> [119] hms_1.1.3                 sparseMatrixStats_1.13.4 
> [121] bit64_4.0.5               Rhdf5lib_1.22.0          
> [123] KEGGREST_1.41.4           statmod_1.5.0            
> [125] rbibutils_2.2.15          Rfast_2.0.8              
> [127] broom_1.0.5               memoise_2.0.1            
> [129] bit_4.0.5                 EnrichmentBrowser_2.31.5 
>

**Comment by GabrielHoffman** [comment]
There was a bug that I fixed in the current version available at https://diseaseneurogenomics.github.io/dreamlet/index.html

Best,
Gabriel

**Comment by AnnaSophieFroehlich** [comment]
Dear Gabriel,

Thank you for your fast reply.

I have now created a new environment and installed the latest version of dreamlet v1.1.1.
I am however still facing the same exact problem.

same code as above.

> celltype…
> 
> Error in weightsMatrix * out$weights: non-conformable arrays
> Traceback:
> 
> 1. processAssays(pb, form, assays = “celltype”, min.count = 10, 
>  .     min.prop = 0.8, min.cells = 5, min.samples = 50, BPPARAM = SnowParam(12))
> 2. lapply(assays, function(k) {
>  .     if (!quiet) 
>  .         message("  ", k, "...", appendLF = FALSE)
>  .     startTime <- Sys.time()
>  .     y <- assay(sceObj, k)
>  .     n.cells <- n.cells_full[colnames(y), k, drop = FALSE]
>  .     data <- merge_metadata(data_constant, metadata(sceObj)$aggr_means, 
>  .         k, metadata(sceObj)$agg_pars$by)
>  .     if (!is.null(weightsList)) {
>  .         weights <- weightsList[[k]][, rownames(data), drop = FALSE]
>  .     }
>  .     res <- processOneAssay(y[, rownames(data), drop = FALSE], 
>  .         formula = formula, data = data, n.cells = n.cells[rownames(data), 
>  .             , drop = FALSE], min.cells = min.cells, min.count = min.count, 
>  .         min.samples = min.samples, min.prop = min.prop, isCounts = isCounts, 
>  .         normalize.method = normalize.method, span = span, weights = weights, 
>  .         BPPARAM = BPPARAM, ...)
>  .     if (!quiet) 
>  .         message(format(Sys.time() - startTime, digits = 2))
>  .     res
>  . })
> 3. FUN(X[[i]], ...)
> 4. processOneAssay(y[, rownames(data), drop = FALSE], formula = formula, 
>  .     data = data, n.cells = n.cells[rownames(data), , drop = FALSE], 
>  .     min.cells = min.cells, min.count = min.count, min.samples = min.samples, 
>  .     min.prop = min.prop, isCounts = isCounts, normalize.method = normalize.method, 
>  .     span = span, weights = weights, BPPARAM = BPPARAM, ...)
> 5. voomWithDreamWeights(y[keep, ], formula, data, weights = precWeights, 
>  .     BPPARAM = BPPARAM, ..., save.plot = TRUE, quiet = quiet, 
>  .     span = span, hideErrorsInBackend = TRUE)
> 
> 

`sessionInfo()`

> R version 4.3.1 (2023-06-16)
> Platform: x86_64-conda-linux-gnu (64-bit)
> Running under: CentOS Linux 7 (Core)
> 
> Matrix products: default
> BLAS/LAPACK: /conda-envs/dreamlet_v2/lib/libopenblasp-r0.3.24.so;  LAPACK version 3.11.0
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> time zone: Europe/Berlin
> tzcode source: system (glibc)
> 
> attached base packages:
> [1] stats4    stats     graphics  grDevices utils     datasets  methods  
> [8] base     
> 
> other attached packages:
>  [1] readxl_1.4.3                HDF5Array_1.30.0           
>  [3] DelayedArray_0.28.0         SparseArray_1.2.1          
>  [5] S4Arrays_1.2.0              abind_1.4-5                
>  [7] Matrix_1.6-2                rhdf5_2.46.0               
>  [9] **dreamlet_1.1.1**              variancePartition_1.32.1   
> [11] BiocParallel_1.36.0         limma_3.58.1               
> [13] ggplot2_3.4.4               zellkonverter_1.12.0       
> [15] SingleCellExperiment_1.24.0 SummarizedExperiment_1.32.0
> [17] Biobase_2.62.0              GenomicRanges_1.54.1       
> [19] GenomeInfoDb_1.38.0         IRanges_2.36.0             
> [21] S4Vectors_0.40.1            BiocGenerics_0.48.1        
> [23] MatrixGenerics_1.14.0       matrixStats_1.1.0          
> 
> loaded via a namespace (and not attached):
>   [1] splines_4.3.1             pbdZMQ_0.3-10            
>   [3] bitops_1.0-7              filelock_1.0.2           
>   [5] cellranger_1.1.0          tibble_3.2.1             
>   [7] basilisk.utils_1.14.0     graph_1.80.0             
>   [9] XML_3.99-0.15             lifecycle_1.0.4          
>  [11] Rdpack_2.6                mixsqp_0.3-48            
>  [13] edgeR_4.0.1               lattice_0.22-5           
>  [15] MASS_7.3-60               backports_1.4.1          
>  [17] magrittr_2.0.3            reticulate_1.34.0        
>  [19] DBI_1.1.3                 minqa_1.2.6              
>  [21] zlibbioc_1.48.0           EnvStats_2.8.1           
>  [23] purrr_1.0.2               rmeta_3.0                
>  [25] msigdbr_7.5.1             RCurl_1.98-1.13          
>  [27] GenomeInfoDbData_1.2.11   ggrepel_0.9.4            
>  [29] pbkrtest_0.5.2            irlba_2.3.5.1            
>  [31] annotate_1.80.0           DelayedMatrixStats_1.24.0
>  [33] codetools_0.2-19          tidyselect_1.2.0         
>  [35] lme4_1.1-35.1             base64enc_0.1-3          
>  [37] jsonlite_1.8.7            iterators_1.0.14         
>  [39] tools_4.3.1               progress_1.2.2           
>  [41] snow_0.4-4                Rcpp_1.0.11              
>  [43] zenith_1.4.0              glue_1.6.2               
>  [45] IRdisplay_1.1             dplyr_1.1.3              
>  [47] withr_2.5.2               numDeriv_2016.8-1.1      
>  [49] BiocManager_1.30.22       fastmap_1.1.1            
>  [51] basilisk_1.14.0           boot_1.3-28.1            
>  [53] rhdf5filters_1.14.1       fansi_1.0.5              
>  [55] caTools_1.18.2            digest_0.6.33            
>  [57] truncnorm_1.0-9           R6_2.5.1                 
>  [59] colorspace_2.1-0          scattermore_1.2          
>  [61] gtools_3.9.4              RSQLite_2.3.3            
>  [63] RhpcBLASctl_0.23-42       utf8_1.2.4               
>  [65] tidyr_1.3.0               generics_0.1.3           
>  [67] data.table_1.14.8         corpcor_1.6.10           
>  [69] prettyunits_1.2.0         httr_1.4.7               
>  [71] pkgconfig_2.0.3           gtable_0.3.4             
>  [73] blob_1.2.4                XVector_0.42.0           
>  [75] remaCor_0.0.16            htmltools_0.5.7          
>  [77] GSEABase_1.64.0           scales_1.2.1             
>  [79] png_0.1-8                 fANCOVA_0.6-1            
>  [81] ashr_2.2-63               reshape2_1.4.4           
>  [83] uuid_1.1-1                nlme_3.1-163             
>  [85] nloptr_2.0.3              repr_1.1.6               
>  [87] cachem_1.0.8              stringr_1.5.0            
>  [89] KernSmooth_2.23-22        parallel_4.3.1           
>  [91] RcppZiggurat_0.1.6        AnnotationDbi_1.64.1     
>  [93] pillar_1.9.0              grid_4.3.1               
>  [95] vctrs_0.6.4               gplots_3.1.3             
>  [97] mashr_0.2.79              xtable_1.8-4             
>  [99] Rgraphviz_2.46.0          evaluate_0.23            
> [101] KEGGgraph_1.62.0          invgamma_1.1             
> [103] mvtnorm_1.2-3             cli_3.6.1                
> [105] locfit_1.5-9.8            compiler_4.3.1           
> [107] rlang_1.1.2               crayon_1.5.2             
> [109] SQUAREM_2021.1            plyr_1.8.9               
> [111] stringi_1.7.12            assertthat_0.2.1         
> [113] babelgene_22.9            lmerTest_3.1-3           
> [115] munsell_0.5.0             Biostrings_2.70.1        
> [117] aod_1.3.2                 dir.expiry_1.10.0        
> [119] IRkernel_1.3.2            hms_1.1.3                
> [121] sparseMatrixStats_1.14.0  bit64_4.0.5              
> [123] Rhdf5lib_1.24.0           KEGGREST_1.42.0          
> [125] statmod_1.5.0             rbibutils_2.2.16         
> [127] Rfast_2.0.9               broom_1.0.5              
> [129] memoise_2.0.1             RcppParallel_5.1.7       
> [131] bit_4.0.5                 EnrichmentBrowser_2.32.0

**Comment by GabrielHoffman** [comment]
Can you provide a minimal reproducible example so I can debug this

**Comment by MukundhMurthy** [comment]
Hey @AnnaSophieFroehlich @GabrielHoffman !

@GabrielHoffman Thank you so much for your work on this package – I'm really excited to perform some analyses with dreamlet.

Coincidentally, I just had the same issue yesterday – I've been following along this thread, created a new environment (with the up-to-date dreamlet version 1.1.1) and am still getting exactly the same error as well.

**Comment by GabrielHoffman** [comment]
Thanks for the bug report.

It looks like I fixed this bug last week but the fix didn't make it into the Bioconductor release.  You can get a new version here: `devtools::install_github("DiseaseNeuroGenomics/variancePartition")`.  I will push the fix to Bioconductor, but it will take a few days to post.

Gabriel

**Comment by AnnaSophieFroehlich** [comment]
Hi Gabriel,

Thanks a lot! 
It works now.
